# Dependencies
markdown:            redcarpet
#markdown:            kramdown
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               solstice.kennethsun.net
tagline:         "Pentesting, Offensive Security Research & Development"
description:         "Pentesting, Offensive Security Research & Development, Python Junkie and Coffee Addict. #Hacking 247."
url:                 http://solstice.kennethsun.net
baseurl:             
paginate:            7

# About/contact
author:
  name:              Gabriel Ryan (solstice)
  url:               https://twitter.com/s0lst1c3
  email:             gabriel@solstice.kennethsun.net

# Custom vars
version:             2.0

# Social Media
github:				http://github.com/s0lst1c3
twitter:			http://twitter.com/s0lst1c3
linkedin:           http://linkedin.com/ms08067

future: true
